### ISSUE TITLE
Gaston apparently doesn't support 'logscale'

### ISSUE THREAD

**Issue by sergstesh** [mbaz/Gaston.jl#106]
I've read the tutorial and I've looked into the code, and apparently Gaston doesn't support Gnuplot logscale property/feature - the one expressed in Gnuplot documentation as

"
Logscale
Syntax:
  set logscale <axes> {<base>}
  unset logscale <axes>
  show logscale
".

If I understand the architecture of Gaston correctly, the problem originates from missing fields in https://github.com/mbaz/Gaston.jl/blob/master/src/gaston_types.jl file; specifically the AxesConf mutable struct doesn't have any filed related to logscale.

**Comment by mbaz** [comment]
The supported way to set an axis to logarithmic is:

    plot(rand(20),axis="semilogy")

You can also use `"semilogx"` or `"loglog"`. I need to add this to the documentation....

**Comment by sergstesh** [comment]
Thanks - 'axis="semilogx"' works for me. Yes, please update the documentation,

**Comment by mbaz** [comment]
Fixed in v0.10.0. See new docs: https://mbaz.github.io/Gaston.jl/v0.10.0/
