### ISSUE TITLE
Underscores and enhanced terminal by default

### ISSUE THREAD

**Issue by sergstesh** [mbaz/Gaston.jl#107]
If one uses Gaston as is and tries to use strings with underscores in title, the underscores are not displayed. Instead the underscores affect the following character turning it into subscript.

This is not a Gaston feature, this is a Gnuplot feature.

I use a lot of names with underscores, so at least for me it's not convenient behavior and I do not think it should be default. The unwanted for me behavior is disabled by issuing from Julia the following before plotting:

Gaston.gnuplot_send("set terminal qt noenhanced")
.

The keyword in the above command is "noenhanced".

I think this should be the default way Gnuplot terminal is initialized by Gaston.

Anyway, regardless of what the default behavior will/should be I think that the issue should be addressed in Gaston documentation.

**Comment by mbaz** [comment]
This is a test case I had not tried before. This works for me:

    plot(rand(20),title="title\\_one")

My plan for the next release is to allow users to configure default terminal options. This would allow you to set the terminal to "noenhanced" if you prefer, while keeping the "better" terminal as the default.

**Comment by mbaz** [comment]
Fixed in https://github.com/mbaz/Gaston.jl/commit/de88e47e6163324544de30599bb1f5b424bd2d9a
