### ISSUE TITLE
Verify tests pass on Windows

### ISSUE THREAD

**Issue by mbaz** [mbaz/Gaston.jl#113]

**Comment by RoyiAvital** [comment]
Does `Gatson.jl` expects the executable of GnuPlot to be on the path?
Could the path to GnuPlot executable be defined in `Gtason.jl` to allow working with GnuPlot without installing it (Just unzip it in a given path)?

**Comment by mbaz** [comment]
@RoyiAvital Currently, Gaston expects gnuplot to be on the path. However, it is easy to add a setting for a path. Would you mind opening a new issue?

In the meantime, you can add a path manually by editing line 62 in `Gaston.jl`.
