### ISSUE TITLE
cannot use "scatter!"

### ISSUE THREAD

**Issue by Photonico** [mbaz/Gaston.jl#114]
I need to use "scatter!" to plot some points in the graph, but Gaston seems doesn't support it.

```
ERROR: LoadError: UndefVarError: scatter! not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] include(::String) at .\client.jl:403
 [6] top-level scope at none:0
in expression starting at d:\Algorithms\Linear Algebra\Geometric Transformation.jl:17
```

**Comment by mbaz** [comment]
Yes, I haven't implemented `scatter!`. I can add it to the next release.

In the mean time, you can use `plot!` with `plotstyle="points"`:

```
plot(rand(10))
plot!(10rand(10),10rand(10),plotstyle="points")  # equivalent to `scatter!`
```

**Comment by ConAntares** [comment]
> 
> 
> Yes, I haven't implemented `scatter!`. I can add it to the next release.
> 
> In the mean time, you can use `plot!` with `plotstyle="points"`:
> 
> ```
> scatter(rand(10),rand(10),pointtpe="∘")
> plot!(10rand(10),10rand(10),plotstyle="points",pointtype="⊕")  # equivalent to `scatter!`
> ```

Thanks a lot for your response.

After a period of trial, I have found some issues:
1. The startup time is too slow;
2. Only a few fonts are supported, I also can't use "CMU-Serif";

And I have some suggestions:
1. Add a statement which aims to control global variables. like ```rcParams``` in Matplotlib;
2. Discard the GUI of Gnuplot, only use its core;
3. Support LaTeX natively.

I hope that I can support you but I am a beginner in programming. So I can only provide some feedbacks.

**Comment by mbaz** [comment]
Thanks for the feedback.

1. Regarding startup time: if you're on Windows, this is a known issue that I cannot fix. See [this thread](https://discourse.julialang.org/t/standard-streams-much-slower-in-windows-than-in-linux/24924). If possible, run Julia on a Linux virtual machine for best overall performance.

2. Regarding fonts:

* Please see the "Fonts" section on [gnuplot's documentation](http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf), page 36. 
* Try to use that font in a Gnuplot session. If you can get it to work there, then please send me your gnuplot commads. For example, in my machine I can set the font successfully running something like `set term qt font "Consolas,14"; plot sin(x)`.

3. Regarding global variables: I don't understand the proposal. Have you seen the documentation for `set()`? How is `rcParams` different?

4. I don't understand what you mean by using only the core. How would the plots be produced then?

5. Do you mean supporting one of the Latex terminals? This is planned for a future release.

**Comment by ConAntares** [comment]
> 
> 
> Thanks for the feedback.
> 
>     1. Regarding startup time: if you're on Windows, this is a known issue that I cannot fix. See [this thread](https://discourse.julialang.org/t/standard-streams-much-slower-in-windows-than-in-linux/24924). If possible, run Julia on a Linux virtual machine for best overall performance.
> 
>     2. Regarding fonts:
> 
> 
>     * Please see the "Fonts" section on [gnuplot's documentation](http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf), page 36.
> 
>     * Try to use that font in a Gnuplot session. If you can get it to work there, then please send me your gnuplot commands. For example, in my machine I can set the font successfully running something like `set term qt font "Consolas,14"; plot sin(x)`.
> 
> 
>     1. Regarding global variables: I don't understand the proposal. Have you seen the documentation for `set()`? How is `rcParams` different?
> 
>     2. I don't understand what you mean by using only the core. How would the plots be produced then?
> 
>     3. Do you mean supporting one of the Latex terminals? This is planned for a future release.

Thank you for your response.

I'm very looking forward to the new version.

**Comment by mbaz** [comment]
Have you read all of Gaston's documentation? Gaston already works in Jupyter. You can also plot ot the terminal using `set(terminal="dumb")`.

Gnuplot.jl is faster in Windows because it doesn't do as much error handling as Gaston.

**Comment by ConAntares** [comment]
> 
> 
> Have you made sure to read all of Gaston's documentation? Gaston already works in Jupyter. You can also plot in the REPL using `set(terminal="dumb")`.
> 
> Gnuplot.jl is faster in Windows because it doesn't do as much error handling as Gaston. But, I'll take another look at how it uses streams.

Thank you very much for your response, I am going to read the doc carefully.

I am a first-year Ph.D. student in Physics, my temporary task is learning scientific programming. I have a strong interest in Julia. I have tried and learned a lot of plotting packages in Julia. Such as GR.jl, Plotly.jl, Plots.jl, PyPlot.jl, PGFPlotX.jl, Makie.jl, etc., I think they are not as powerful as Gnuplot. So I hope that we can use Gnuplot in Julia like we use Matplotlib in Python. 

I think one of the reasons for the success and popularity of this Matplotlib is that its detailed documents(about 3000pages), amount of examples in its official website, and various tutorials. I hope that Gaston.jl can be so popular too.  another reason is that there are dozens of people to maintain Matplotlib. I think that you can seek cooperation...

Sincerely,
