### ISSUE TITLE
timeout is too short

### ISSUE THREAD

**Issue by jxy** [mbaz/Gaston.jl#118]
Surface plot in a qt term always take longer on my computer, especially with larger sample/isosample.  The setting for timeout is too optimistic in my opinion for something that throws error.

https://github.com/mbaz/Gaston.jl/blob/fb0ac116886d7d7d89633f8934058c94a0ad174b/src/Gaston.jl#L29

Perhaps just print out a warning every couple of seconds and keep reading until EOF?

**Comment by jxy** [comment]
No.  It's macOS with qt term.
Simply doing `surf(x, y, (x,y)->besselj0(y)*x^2, plotstyle="pm3d", gpcom=postcomm)` takes a couple of seconds at the first launch.  Subsequent runs still take about a second.

**Comment by mbaz** [comment]
How many points are you plotting?
Also: can you run the test described here and post the results (maybe in a gist if they're too long): https://discourse.julialang.org/t/standard-streams-much-slower-in-windows-than-in-linux/24924/3

**Comment by jxy** [comment]
It seems the initialization of the QT term takes a long time when there are lots of fonts available.

**Comment by mbaz** [comment]
That would explain the issue. As a workaround, you may want to try the 'aqua' terminal which is native to MacOS.

I will add a command to allow the user to set the timeout. It'll be out in the next release.

**Comment by jxy** [comment]
Just to let you know that I'm also hitting this on my FreeBSD box with wxt term.  It's just that the first plot takes a lot longer.  Subsequent plots are fine.

**Comment by mbaz** [comment]
@jxy I'll hurry with an update -- I've just been too busy lately.
