### ISSUE TITLE
Possibility to set default config file

### ISSUE THREAD

**Issue by isentropic** [mbaz/Gaston.jl#120]
Dear @mbaz, this is probably the best plotting package for Julia, Plots.jl Makie.jl look horrible even after all customizations I tried to apply. 

Is there a way to set up a config file for the default font, grid, tic style ...?
Better to integrate with native Gnuplot binary even somehow?

**Comment by isentropic** [comment]
Actually, there exists systemwise .gnuplot rc, I'll check if that RC is used when using it through Gaston.

**Comment by mbaz** [comment]
@isentropic Thank you for the kind words.

Indeed, Gaston respects your .gnuplot configuration file. It is loaded before every plot. In addition, you can change the value of any Gaston parameter using `set`. If you want a parameter to be always set to some value, you can add a `set` command to your `.juliarc.jl` file.

The documentation is here: https://mbaz.github.io/Gaston.jl/v0.10.0/

**Comment by isentropic** [comment]
Yes, it indeed works
