### ISSUE TITLE
Interactive Plots in Jupyter

### ISSUE THREAD

**Issue by isentropic** [mbaz/Gaston.jl#121]
Is there a possibility to have Interactive (zoom, pan) plots in Jupyter?
ATM, Gaston only plots plain images into notebooks.

**Comment by mbaz** [comment]
It *is* possible, according to the documentation; I've just never had a chance to implement it.

I'll look into it, but it may take some time. I'll accept a pull request implementing this; you should start with the documentation for the svg terminal, page 248 in the [manual ](http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf).

**Comment by mbaz** [comment]
See https://github.com/mbaz/Gaston.jl/issues/146 for current difficulties implementing this. At least in the short term, this appears impossible to implement within the scope of Gaston.
