### ISSUE TITLE
Date as x-axis

### ISSUE THREAD

**Issue by waynelapierre** [mbaz/Gaston.jl#122]
I work with a lot of panel data and I would like to know how to plot my data with dates as input for x-axis in Gaston. Thanks.

**Comment by mbaz** [comment]
Gnuplot supports this (see page 50 in the manual, http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf) but this functionality is not exposed by Gaston. I will accept a PR to implement this.

How do you work with dates in Julia? Is there a package you use, or is it part of the standard library?

**Comment by mbaz** [comment]
There is an example here: https://mbaz.github.io/Gaston.jl/stable/2d-gallery/#Plotting-times/dates-1
