### ISSUE TITLE
No printfigure in jupyter

### ISSUE THREAD

**Issue by isentropic** [mbaz/Gaston.jl#123]
An attempt to save figures in jupyter gives:
```
printfigure command disabled in Jupyter notebook.
```

**Comment by mbaz** [comment]
Yes -- I've never had a chance to test if we can print from Jupyter. I will test this soon.

**Comment by NoelAraujo** [comment]
I got the same error with Juno (not Jupyter). 
I just hacked the code and comment the line 406 of the file `gaston_hilvl.jl` 
`#IsJupyterOrJuno && error("printfigure command disabled in Jupyter notebook.")`.

After building Gaston package again, I can save the figure. I hope this information helps

**Comment by mbaz** [comment]
@NoelAraujo It does help -- thanks. As soon as I have a little bit of free time I'll release a new version including this change.
