### ISSUE TITLE
MWE for a complete figure

### ISSUE THREAD

**Issue by lazarusA** [mbaz/Gaston.jl#126]
Great work... so far everything is fast and it looks nice... but..

How looks like a MWE for a figure, from calling Gaston to save it?
It seems that something is wrong with the saving option? In my case I just get some lines and not the whole plot. 

Also, if I run one simple script the plot it's not displayed in a new window...

**Comment by mbaz** [comment]
@lazarusA Thanks for the kind words!

Have you seen this? https://mbaz.github.io/Gaston.jl/v0.10.0/2dplots/#Saving-plots-1

If you give me more details, I can investigate the problem when saving plots. What terminal? What are you plotting? What's the exact command you use to save the plot?

For your second question: what do you mean by "run one simple script"? Do you run it from the command line with `julia -L`? Or do you want each `plot` to produce a new window? (See https://mbaz.github.io/Gaston.jl/v0.10.0/notes/#How-to-keep-multiple-plots-(figures)-on-screen-at-a-time?-1)

**Comment by lazarusA** [comment]
Hello, 
yes I tried the following in Julia 1.3.0

```
using Gaston
set(terminal="aqua")
t = 0:0.01:1
fig1 = plot(t, sin.(2π*5*t), title="Waves", grid="on", plotstyle = "lines",
    xlabel="Time(s)", ylabel="Amplitude (V)", legend="sin(t)" )
printfigure(term="pdf", font="Consolas,10", size="600,400",
        linewidth="1", outputfile="fig1.pdf")
```
and the figure its just wrong. 

Regarding the script. I was expecting to run the same code from an file as 
` 
$ julia file.jl 
`
and get the figure in a new window. But no, as you said, I need to pass `-L` and then call for the corresponding figure in the julia session.

**Comment by lazarusA** [comment]
After playing around this weekend with `Gaston` I can say that I'm able to reproduce most of the basic plots for publication(that I use). Things will be better if only this section of gnuplot (http://gnuplot.sourceforge.net/demo/varcolor.html) were available, perhaps via `gpcom` but I was not able to figure out a way to do it. If you have an easy hack I could code some  basic (including docs in a PR) examples like in Plots (even with the same syntax).

**Comment by mbaz** [comment]
Once thing you need to be aware of is that, for saving as pdf, the size is given in inches. You are saving a _huge_ plot.

Try changing the size to `size="5,3"`. Please let me know if that helps.

**Comment by lazarusA** [comment]
Yes, that was the problem... going to inches. Thanks. Looking forward for new features.. specially the colouring part that I mentioned above. All the best!

**Comment by mbaz** [comment]
Are you aware that you can define your own linetypes in gnuplot's startup file? See https://mbaz.github.io/Gaston.jl/v0.10.0/#gnuplot-configuration-1

Would that be enough for your needs?

**Comment by lazarusA** [comment]
Yes, I'm.
 However, I think it will be better to be able to simply call `lc pal z`,  or `lc var` for coloring for example scatters with a third column of variables as in pure gnuplot or as is usually done in Plots's syntax `(linez)` (keyword) more than defined everything before hand. Or being able to put a colormap(palette) in a line with `lc pal`. (http://www.gnuplotting.org/using-a-palette-as-line-color/) I was under the impression that this could be possible with your `gpcom` argument.  

By the way how the third or four example from (http://gnuplot.sourceforge.net/demo/varcolor.html) will look like with your suggestion?. It doesn't look that obvious. IMO.

**Comment by mbaz** [comment]
I'm having trouble imagining how to use `lc variable`. If you execute a regular `plot` command, how do you specify the additional column for the line type? Should `plot` take an additional argument? How do you imagine it working? (The same goes for `lc pal z`).

I'm open to implementing this, but we need to figure out a way to interface with these commands.

I'm also open to accepting PRs implementing this :)

**Comment by lazarusA** [comment]
I imagine that the most natural way to do this is to have an extra keyword, as in the Plots recipes ecosystem. Where this is usually achieved by passing values to the argument `linez = ...` and specifying the corresponding colormap to use, in the language of gnuplot, a palette.

**Comment by lazarusA** [comment]
at the moment I cannot offer much help. I'm still getting familiar with the Gaston interface to gnuplot. But the idea is to have at the end 3 columns available of values and passed them to `plot`  in gnuplot. So far you only pass 2 for 2D plots. (Although, you already have some recipes for 3, in the contour and surf functions).

**Comment by lazarusA** [comment]
Never mind. Probably there is no need for such things. I was able to do it with your `plot` definition in two lines of code. Keep up the good work and good luck !

**Comment by mbaz** [comment]
@lazarusA Thanks for the feedback, and please report back any issues you find or any ideas for improvement.
