### ISSUE TITLE
terminal epslatex 

### ISSUE THREAD

**Issue by lazarusA** [mbaz/Gaston.jl#127]
Hello,
how hard is to include the epslatex terminal?. I suppose that by doing it, it will possible to add labels and equations with the latex syntax.

**Comment by mbaz** [comment]
Not too hard, but not straightforward either, because currently there is no way to specify an output file name. `Cairolatex` might be a more modern option, but I need to research this more.

**Comment by mbaz** [comment]
@lazarusA Please stand by... I should have something working soon.

**Comment by lazarusA** [comment]
I mean, this only helps if the Latex support is possible. Otherwise I think it will be not worth it.

**Comment by mbaz** [comment]
@lazarusA What is possible with gnuplot is to have a plot with latex labels (title, axis, etc.). Gnuplot will produce two files (one `.tex` and one `.eps`). You need to `include` the  `.tex` file in your own Latex document, compile it, and that will actually produce the plot.

As far as I know, this is the only way you can have Latex labels in a plot using Gnuplot. Please let me know if this is acceptable to you; if it is, I can implement it within one day or two.

**Comment by lazarusA** [comment]
Yes, that's what I mean. And more than useful to me is for the community. I think this is something that will be pretty convenient to have.

**Comment by mbaz** [comment]
Alright -- I'm on it.

**Comment by mbaz** [comment]
@lazarusA You can try the new terminals if you install Gaston master:

`Pkg> add Gaston#master`

and then you can run:

```
set(terminal="epslatex") # or cairolatex
set(output="test.tex")  # filename
plot(1:10)
```
and you should see two new files in your current directory: `test.tex` and `test.eps`.

Let me know if you have any problems.

I'll release 0.11 soon, but I need to write the documentation first... will take me a few days.
