### ISSUE TITLE
contour color lines

### ISSUE THREAD

**Issue by lazarusA** [mbaz/Gaston.jl#128]
Hello, 
any advice on how to use the set the same color map for the lines as in the colorbar? In pure gnuplot looks easy but I don't see how to do it here. (https://stackoverflow.com/questions/17700262/gnuplot-how-to-obtain-contour-lines-with-the-same-level-color-of-the-3d-plot)

```
using Gaston
set(terminal="aqua")
fc(x,y) = x.^2 .+ y.^2 .- 2x .- 6y .+ 14
x = y = LinRange(-12,12,100)
surf(x, y, (x,y)-> fc(x,y),
    plotstyle="pm3d", size = "400,400", gpcom = 
    """
    unset surface
    set view map
    set contour base; unset key
    set cntrparam levels 20
    """)
```

**Comment by mbaz** [comment]
The example in stackoverflow doesn't work for me in gnuplot 5.2 -- all contour lines are cyan.

I don't know how to accomplish this in gnuplot, but if you can figure it out there, you should be able to reproduce it with Gaston.

Also: please ask support questions in Discourse with the `visualization` tag (https://discourse.julialang.org/c/domain/viz/17). That way, more people can chime in and benefit, and the issue list here remains focused on actual issues.
