### ISSUE TITLE
Plot doesn't appear in front of other windows

### ISSUE THREAD

**Issue by PallHaraldsson** [mbaz/Gaston.jl#134]
I mean it does the first time, and even on master, with the second plot (whether or not I closed the old plot window), I only get a notification in Ubuntu, and have to click on it to bring the plot windows to front.

FYI:I wasn't sure if this was an Ubuntu window manager thing, but at least this doesn't happen with <s>Gnuplot.jl and</s> GR.jl on same OS.

**Comment by mbaz** [comment]
I can't reproduce. I run Openbox and every `plot` command raises the plot window to the front.

I'll see if Gnuplot.jl is doing anything differently, but since windows are controlled by gnuplot, I'm not sure what that could be.

**Comment by PallHaraldsson** [comment]
Sorry, it's only GR.jl that's ok. I seem to remember Gnuplot.jl ok too, but either I'm mistaken or it's flaky. Doesn't work for me now. I've also been trying different versions, and tried master again just in case.

**Comment by PallHaraldsson** [comment]
However Gnuplot.jl has this awesome feature: https://gcalderone.github.io/Gnuplot.jl/v1.2.0/terminals/#Plot-in-a-terminal-application-(dumb,-sixel-and-sixelgd)-1 with the right terminal.

**Comment by PallHaraldsson** [comment]
I for sure should be using qt too in the other package, and haven't gotten "set term wxt size 800,600" to work there (I mean I can put it in the gnuplot REPL mode, but get an error).

I'm not sure it would help, as you confirmed it's an "Ubuntu" issue, at least partially. But GR works. Not sure what's it built on (maybe not QT if that's part of the problem?).

**Comment by mbaz** [comment]
@PallHaraldsson Gaston also supports plotting on a terminal. You can use either the "dumb" terminal to get an ASCII plot, or "sixelgd" if your terminal supports sixels. See https://discourse.julialang.org/t/plots-in-the-terminal-with-sixel/22503/11?u=mbaz
