### ISSUE TITLE
3D vector support

### ISSUE THREAD

**Issue by sriharitn** [mbaz/Gaston.jl#140]
Thank you for awesome package. Currently there is no plot facility in Julia that supports it. It would be great to import gnuplot facility into Gaston. As an example please see below gnuplot for 3D vector field.

`splot 'file.dat' using 1:2:3:(1):(1):(1) with vectors filled head lw 2`

**Comment by mbaz** [comment]
This is possible right now:

    x = 2rand(10);
    y = 2rand(10);
    z = 2rand(10);
    surf(x, y ,z, u = "1:2:3:(1):(1):(1)", w = "vectors filled head", lw=2,
           Axes(xlabel = :x, ylabel = :y, zlabel = :z)

This produces:
![image](https://user-images.githubusercontent.com/1630034/90338586-abf29600-dfb8-11ea-8039-2a887213a95f.png)

Please reopen this issue if you hit any roadblocks.

**Comment by mbaz** [comment]
If you want to write a recipe for this kind of plot, please see: https://mbaz.github.io/Gaston.jl/stable/extending/  -- if you submit a PR with the recipe, I will likely accept it. Otherwise, I may add a recipe myself in a new release.

**Comment by sriharitn** [comment]
Thank you. Here is what I'm trying to do:

```
using Gaston
x = [-5 ,-4.552786405 ,-4.105572809 ,-3.211145618 ,-1.422291236 ,0]
y = [10 ,9.105572809 ,8.211145618 ,6.422291236 ,2.844582472 ,0]
z = [125 ,103.6393202 ,84.27864045 ,51.5572809 ,10.1145618 ,0]
dx = [0.447213595 ,0.447213595 ,0.894427191 ,1.788854382 ,1.422291236 ,0]
dy = [-0.894427191 ,-0.894427191 ,-1.788854382 ,-3.577708764 ,-2.844582472 ,0]
dz = [-21.36067977 ,-19.36067977 ,-32.72135955 ,-41.4427191 ,-10.1145618 ,0]


Gaston.surf(x, y, z,dx,dy,dz, u = "1:2:3:4:5:6",w = "vectors filled head", lw=2,
       Axes(xlabel = :x, ylabel = :y, zlabel = :z))
```

I get an error: 

```
MethodError: no method matching surf(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Axes; u="1:2:3:4:5:6", w="vectors filled head", lw=2)
Closest candidates are:
  surf(::Any, ::Any, ::Any) at 
[circle.txt](https://github.com/mbaz/Gaston.jl/files/5080978/circle.txt)

  ...
top-level scope at simple2.jl:118
```

Here is same in gnuplot:


```
$data << EOD                     
-5 10 125 0.447213595 -0.894427191 -21.36067977
-4.552786405 9.105572809 103.6393202 0.447213595 -0.894427191 -19.36067977
-4.105572809 8.211145618 84.27864045 0.894427191 -1.788854382 -32.72135955
-3.211145618 6.422291236 51.5572809 1.788854382 -3.577708764 -41.4427191
-1.422291236 2.844582472 10.1145618 1.422291236 -2.844582472 -10.1145618
0 0 0 0 0 0
EOD

splot $data u 1:2:3:4:5:6 with vectors filled head 
```
Produces following output:

![sample_gnuplot](https://user-images.githubusercontent.com/40153228/90339051-338dd400-dfbc-11ea-9b0d-cdab6edd72bd.png)

**Comment by sriharitn** [comment]
Here is the question that I raised in discourse.julia website:

(https://discourse.julialang.org/t/3d-quiver-plot-and-animation/44645)

**Comment by mbaz** [comment]
As explained in the manual, `surf` takes only three coordinates as arguments; additional data must be passed using the `supp` argument:

    surf(x, y, z, supp = [dx dy dz], w = "vectors filled head", lw = 2)
