### ISSUE TITLE
Point Gaston to gnuplot

### ISSUE THREAD

**Issue by jleman** [mbaz/Gaston.jl#142]
Is it necessary to manually point Gaston.jl to gnuplot?  I installed gnuplot successfully using the windows 64 installer on sourceforge.  Then I added Gaston.jl in Julia.  When prompted I selected the option to add gnuplot to Windows PATH. I the get the following error upon execution of  `using Gaston`

┌ Warning: Gnuplot is not available on this system. Gaston will be unable to produce any plots.
└ @ Gaston C:\Users\jleman\.julia\packages\Gaston\FSgDg\src\Gaston.jl:88

**Comment by mbaz** [comment]
It shouldn't be necessary if gnuplot is added correctly to your PATH.

Try this: open a terminal and run `gnuplot` from it. If it doesn't work, then it's not in your PATH. If it works, then Gaston should find it as well. Make sure to start a fresh Julia session after installing `gnuplot`.

**Comment by jleman** [comment]
> It shouldn't be necessary if gnuplot is added correctly to your PATH.
> 
> Try this: open a terminal and run `gnuplot` from it. If it doesn't work, then it's not in your PATH. If it works, then Gaston should find it as well. Make sure to start a fresh Julia session after installing `gnuplot`.

Ok. Wouldn't run from terminal even though I had checked the option to be added to path.  However, I had the wrong terminal option set.  I corrected that (selected the Windows option) on re-install and it is now working.  Looks like a very capable plot program.  Not sure why I have never heard of gnuplot before.  Looking forward to having access to this in Julia.

**Comment by mbaz** [comment]
You're very welcome, I'm glad you got it to work.
