### ISSUE TITLE
Consider adding a plot size kwarg to the plot() function.

### ISSUE THREAD

**Issue by jleman** [mbaz/Gaston.jl#144]
Consider placing the functionality for this code:
`set(termopts="size 600,500")` 

in the plot() function.  Something like:  
`plot(x,y,size=(600,500))`

**Comment by mbaz** [comment]
There are two difficulties here:

* `size` outiside a `set terminal` command already means something to gnuplot. The two uses of `size` need to be disambiguated somewhow.
* Currently Gaston builds a terminal command separate from the plot command. This can be changed but involves a bit of plumbing.

However, I think this could help to simplify Gaston's commands and make the interface more uniform. I'll seriously consider this for the 2.0 release.

**Comment by mbaz** [comment]
I've decided that, for consistency, this needs to be set in the `term` config option, for example:

    set(term = "pdf size 5,3")

or

    set(term = "qt size 800,600")
