### ISSUE TITLE
Feature request - smooth plot in Gaston

### ISSUE THREAD

**Issue by clad26** [mbaz/Gaston.jl#148]
Is making "fit" into a function and smooth into a parameter possible？

**Comment by mbaz** [comment]
You can use `smooth` already:

    plot(rand(20), smooth="csplines")

![image](https://user-images.githubusercontent.com/1630034/96063081-2038a100-0e65-11eb-874f-d80125642750.png)

**Comment by mbaz** [comment]
Supporting `fit` is difficult. I suggest implementing a fitting algorithm in Julia itself, and using Gaston to plot it.

**Comment by clad26** [comment]
Do you mind updating the docs then？

**Comment by clad26** [comment]
If there's any other function that Gaston has, which is not there in the docs, would you check them and update the docs？

**Comment by clad26** [comment]
Does Gaston support every feature of gnuplot as a keyword（other than fit, which has smooth as an alternative）？

**Comment by mbaz** [comment]
It doesn't support everything -- but it does support everything related to "data" plots where the data is in the form of a numerical table.
