### ISSUE TITLE
using curveconf makes legend and lc and a few other keywords unusable！

### ISSUE THREAD

**Issue by clad26** [mbaz/Gaston.jl#149]
I hope that the use and need of curveconf is deprecated in one of the future releases of Gaston. 
It produces some bugs, plus its very similar to writing gnuplot code, which Gnuplot.jl can already do...

**Comment by mbaz** [comment]
Can you clarify what the issue is?

`curveconf` is a convenience argument to pass a string directly to gnuplot. You don't have to use it.

**Comment by clad26** [comment]
plot(x,y,lc=:turquoise, legend=:A_plot, curveconf="smooth csplines")
lc and legend get ignored...
The plot is without legend or with the weird temporary variable name, and line color is still dark blue.

**Comment by mbaz** [comment]
I see now. `curveconf` overrides all other configuration, since otherwise you could easily introduce errors, for example in `plot(y, lc=:turquoise, curveconf="lc 'red'")`.

As I pointed out in one of your other issues, the correct syntax is `plot(y, lc=:turquoise, legend=:A_plot, smooth="csplines")`.

**Comment by clad26** [comment]
Thanks! The keywords of Axes become set command, the parameters of plot are keywords themselves. Didn't know that!
In this way, I guess that Gaston gives almost all functionality of Gnuplot other than fit command, makes everything able to be used in function format. 
I'm closing this since my issue is resolved. Thanks a lot again!

**Comment by mbaz** [comment]
You're welcome. I will see if I can make this clearer in the documentation.
