### ISSUE TITLE
Polar plots?

### ISSUE THREAD

**Issue by clad26** [mbaz/Gaston.jl#150]
Any support for, set polar, in Pluto? It can be done with Axes(polar="")
Specifically, how do I do something like 
```
gnuplot> set polar
gnuplot> plot 0.5,1,1.5
```
in Gaston? Thanks!

**Comment by mbaz** [comment]
plot(0:0.1:2π, sin.(2 .*(0:0.1:2π)), Axes(polar=true, grid=true, size="square"))

If you want `set polar` to be sent to gnuplot, you need `Axes(polar=true)` in Gaston.

Please consider asking support questions in Discourse.
