### ISSUE TITLE
Some markers don't appear to work on Mac

### ISSUE THREAD

**Issue by jlchan** [mbaz/Gaston.jl#155]
The following code 
```
using Gaston
set(term = "aqua")
x = 0:.1:6*pi
scatter(x,sin.(x), pt = "fcircle")
```
gives this plot
<img width="958" alt="Screen Shot 2020-11-04 at 12 46 58 PM" src="https://user-images.githubusercontent.com/1156048/98155426-d5c2a700-1e9b-11eb-9991-03def9fd78e2.png">

There's some other odd behavior - 'ecircle' and 'edmd' plot 'etriangle', while 'etriangle' plots 'e'. 

The dot, +, x, * symbols seem fine though.

**Comment by mbaz** [comment]
Could you please run this test: start gnuplot on a terminal, and run:

    set term aqua
    test

and send me a screenshot? What I need is the index to pointtype mapping on the right hand side. I'm thinking that the order is different than in other terminals.

**Comment by jlchan** [comment]
Sure - here it is

![Uploading Screen Shot 2020-11-04 at 7.55.29 PM.png…]()

**Comment by mbaz** [comment]
Thanks. Just as I expected, they are different from qt. [This function](https://github.com/mbaz/Gaston.jl/blob/fffbedbc01fc0a802bf2406928d37d4f30ae3f56/src/gaston_aux.jl#L412) needs to be fixed to return the correct mapping when the terminal is `aqua`. I'll get to this, but a PR'd be welcome too :)

**Comment by jlchan** [comment]
Thanks for letting me know. I can give it a shot this weekend (need to practice my PRs in any case)

**Comment by mbaz** [comment]
You can do `if config[:term] == "aqua"`.

By the way, if you need to plot with markers now, you can use the numbers shown in the `test` screen directly. The marker names are only provided as a convenience.

**Comment by jlchan** [comment]
actually, I just realized from the screenshot that there aren't any options for "fcircle" on aqua. It's not a Gaston issue, it's a Mac and aqua issue...
