### ISSUE TITLE
Zoom and moving around with mouse for Gaston plots, in Pluto

### ISSUE THREAD

**Issue by clad26** [mbaz/Gaston.jl#156]
These two basic functionalities are available easily with svg terminal....
Also, svg terminal is clearer than png one for quality so you might wanna consider that for default.... 

Also, I did try 
set(preamble="set terminal svg size 600,400 dynamic enhanced mousing"), while the size parameter worked, the others didnot.
So.... any way I can implement this myself in Gaston?

**Comment by mbaz** [comment]
Please don't ask multiple questions in one issue; it becomes difficult to keep track of them. Also, I'd prefer if you asked support questions in Discourse.

You had already opened an issue about support for SVG interactivity in Pluto  [here](https://github.com/mbaz/Gaston.jl/issues/146). The situation has not changed.

Don't use the preamble to set terminal options. Rather, use `termopts`. This is explained in the documentation: https://mbaz.github.io/Gaston.jl/stable/faq/#How-to-set-the-terminal-1

**Comment by clad26** [comment]
The last issue required a lot of hard work
This one is just 
``` set term svg enhanced dynamic mousing ```
Easy to implement

Also, in Gaston, with ``` 	set(term = "svg", termopts="size 600,400 dynamic enhanced mousing") ```
Doesn't work
Instead I get this
```
┌ Warning: Gnuplot returned an error message:
│   
│ gnuplot> set term pngcairo size 600,400 dynamic enhanced mousing
│                                         ^
│          line 0: unrecognized terminal option
│ 
└ @ Gaston ~/.julia/packages/Gaston/ctAQy/src/gaston_llplot.jl:182
```
The closest I got was with preamble...

**Comment by clad26** [comment]
The plots produced with 
```  set term svg enhanced dynamic mousing ```
already have zooming and dragging functionality automatically, when displayed on a website... You can try it yourself or look at the http://gnuplot.sourceforge.net/demo_svg_5.5/simple.html

**Comment by clad26** [comment]
Also, this works, only the size parameter though
```	set(showable="svg", termopts="size 1000,400 dynamic enhanced mousing") ```


I think its forced on pngcairo on both ijulia and pluto! 
![Screenshot from 2020-11-15 00-43-59](https://user-images.githubusercontent.com/51269425/99155196-c2091300-26db-11eb-9546-9b744e9941b4.png)

Is that intentional or a bug?

**Comment by clad26** [comment]
@mbaz 
Should I open an issue for it?😅

**Comment by mbaz** [comment]
To enable SVG plotting, you need a Pluto cell with:

    begin
        set(term="svg")
        set(showable="svg")
        set(termopts="dynamic enhanced mousing size 800,600")
    end

However, as explained in https://github.com/mbaz/Gaston.jl/issues/146, you will not get an interactive plot, because Pluto does not execute the javascript embedded in the SVG.

**Comment by clad26** [comment]
@mbaz 
html"<embed src=\"http://gnuplot.sourceforge.net/demo_svg_5.5/simple.2.svg\"></embed>"
Try it in Pluto!!! Works great!
I'm asking if you can make Gaston display images "by default" using this?
Thanks!

**Comment by clad26** [comment]
The above displays svg in Pluto, which can be zoomed dragged and the 2d coordinates are there on mouse pointer

**Comment by clad26** [comment]
@mbaz Can you confirm if I can do this by default in Gaston?

**Comment by mbaz** [comment]
See https://github.com/fonsp/Pluto.jl/issues/546

Support for raw SVG output embedded in an HTML page will be supported in v1.1.0.

**Comment by clad26** [comment]
Thanks😁

**Comment by mbaz** [comment]
This is working on my private development branch. Not available yet, but I wanted to let you know. This branch will become v1.1.0 in (I hope) a couple of weeks.
