### ISSUE TITLE
Please clarify documentation on how to produce line-only plots and maybe update defaults

### ISSUE THREAD

**Issue by sergstesh** [mbaz/Gaston.jl#160]
It may well be I missed something in the documentation - in such a case this report is invalid.

The essence of the problem is that I want a simple y - f(x) plot (whatever 'f') drawn as line only - no characters like '+', 'x', '*', '.' etc. I achieved the goal using the following commands:

```
using Gaston;

closeall();

set(term = "x11");

y = vcat(1:10) .* 1.0;
_1_ = plot(1.0 .* y, curveconf = "w lp pt ' '")
figure()
display(_1_)

```
. The key item is "pt ' '", i.e. single space in single quotes after 'pt'.

So, if this info is missing in the documentation, please add it. Thanks in advance.

Maybe this should be the default. Nowadays in interactive work terminals support color (I think it will take a huge special effort to find a monochrome display nowadays), so I differentiate different plots in the same window using different colors. The colors are well described in the documentation.

**Comment by mbaz** [comment]
Gaston does not have any defaults, except the terimnal type. To configure gnuplot, use a configuration file as explained [here](https://mbaz.github.io/Gaston.jl/stable/#Gnuplot-configuration-1).

To plot using lines and no markers, use the plot style `with lines` (or `w l`). `linespoints` specifies lines and markers ("points" in gnuplot parlance). This is explained in gnuplot's documentation.
