### ISSUE TITLE
Add Support for Defining the Path for GnuPlot Bin Folder by a System Variable

### ISSUE THREAD

**Issue by RoyiAvital** [mbaz/Gaston.jl#176]
See https://github.com/mbaz/Gaston.jl/discussions/175.

**Comment by mbaz** [comment]
Aiming to include this is in the upcoming v2.0 release.

**Comment by mbaz** [comment]
Fixed in main branch, will appear in v2.0.

**Comment by RoyiAvital** [comment]
Any chance to backport it to the current release?

**Comment by mbaz** [comment]
I'm focusing on v2.0, which is almost done. However, it shouldn't be difficult to backport.

If you could prepare a PR, it'd be a huge help. Otherwise, I can do it, but it might take a few days.
