### ISSUE TITLE
Warning when saving figure

### ISSUE THREAD

**Issue by supernovaZhangJiaXing** [mbaz/Gaston.jl#177]
When I tried to save a figure by `save(term="png", output="test.png")`, I got a warning message: 
```
┌ Warning: Gnuplot returned an error message:
│
│ gnuplot> t output 'test.png'
│          ^
│          line 0: invalid command
│
└ @ Gaston C:\Users\Supernova\.julia\packages\Gaston\ly9sC\src\gaston_llplot.jl:182
```
Maybe there is something wrong around the transfer between Gaston and gnuplot.

**Comment by mbaz** [comment]
@supernovaZhangJiaXing What operating system are you using?

**Comment by supernovaZhangJiaXing** [comment]
The OS is win10, versioninfo() returns:
```
Julia Version 1.8.1
Commit afb6c60d69 (2022-09-06 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 2700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver1)
  Threads: 1 on 16 virtual cores
```

**Comment by mbaz** [comment]
I've seen this Windows issue before. Unfortunately, I don't have a solution. I had a lengthy chat with gnuplot's developers about this and we couldn't figure out the cause. The more likely explanation is that `libuv` (which handles all Julia IO) behaves differently on Windows than gnuplot expects.

The real solution is to wait for Gaston v2.0, which is nearing completion. It handles communication with gnuplot in a more robust way, and should avoid this issue. The changes are not straightforward to backport to 1.x, though.
