### ISSUE TITLE
Add Base.writemime methods for export

### ISSUE THREAD

**Issue by stevengj** [mbaz/Gaston.jl#18]
We've recently added a [general API for multimedia I/O](http://docs.julialang.org/en/latest/stdlib/base/#multimedia-i-o) to Julia's standard library.  What this allows you to do is to write a `writemime` method for any of your types that exports it to any MIME type you know how to write, and then `display(x)` on that type will automatically display it on any supporting display that has been loaded.   In particular, the upcoming [IJulia front-end](https://github.com/JuliaLang/IJulia.jl) hooks up with IPython to enable inline display of SVG, PNG, and JPEG graphics.

This way, you only need to supply a `writemime` method to enable multimedia display, and don't need to worry about managing windows or GUIs.

It would be nice to add some support to Gaston for this, at least to allow inline display in IJulia.  What is needed is:
* A ```writemime(io::IO, ::@MIME("image/svg+xml"), x::Figure)``` that writes a figure to `io` as SVG (and similar for PNG etcetera) using Gnuplot's export functions.  Right now, it looks like you use integers as your figure handles, so you may need to wrap a new `Figure` type around these handles.
* If the current display supports images (if `displayable("image/svg+xml") || displayable("image/png")` is `true`), you might consider having `plot` and similar functions simply call `redisplay(x)` on your `Figure` handle instead of asking GnuPlot to pop up a window.  This will allow e.g. inline plots in IJulia by default.

**Comment by mbaz** [comment]
Gaston only supports PNG files with IJulia, though. I think it is enough, but if there is need for more file formats, this issue can be revisited.
