### ISSUE TITLE
demo for financebars seems to have switched low and high values

### ISSUE THREAD

**Issue by akostadinov** [mbaz/Gaston.jl#180]
[Docs](https://docs.w3cub.com/gnuplot/financebars.html) list as column order:

> date  open  low  high  close

but lines in [finance.dat](https://raw.githubusercontent.com/gnuplot/gnuplot/master/demo/finance.dat) are like:

> 2/27/2003	77.9	78.59	76.75	77.28	9927900	0	-4208566	0	0	0

Clearly `78.59 > 76.75` so low and high have switched places.

**Comment by mbaz** [comment]
Thank your for reporting this! I'll take a look (it will take me a few days).

**Comment by mbaz** [comment]
@akostadinov Looking more closely, it seems like this is actually a bug in gnuplot and not in Gaston. Here's [some info on reporting gnuplot bugs](http://www.gnuplot.info/faq/index.html#x1-680007.2). Please re-open if I'm misunderstanding something.
