### ISSUE TITLE
gnuplot not available

### ISSUE THREAD

**Issue by TomVCG** [mbaz/Gaston.jl#20]
Hi,

I'm trying to use the Gaston package, but when I press using Gaston, Julia says gnuplot is not available on this system. I opened the ENV["PATH"], the directory for gnuplot is not in the list, but I can't seem to get it to be added to the list.

I'm new to the language, so it could be I'm missing something straightforward, but I can't seem to find a solution that works.

please help.

**Comment by mbaz** [comment]
@TomVCG Have you figured out a solution? Can we close this issue?
