### ISSUE TITLE
inline plot support for IJulia

### ISSUE THREAD

**Issue by berceanu** [mbaz/Gaston.jl#28]
is there support for inlining plots in an IJulia notebook, as one can do with PyPlot/matplotlib?
i have something like this in mind (seems IRuby can do it)
http://nbviewer.ipython.org/github/minad/iruby/blob/master/IRuby-Example.ipynb
however im not sure if this should be a Gaston feature request or an IJulia one

**Comment by mbaz** [comment]
Fixed in https://github.com/mbaz/Gaston.jl/commit/4fe4581bb34562c4f8f297518dd190b5359d8c40
