### ISSUE TITLE
not possible to set plotting range on `imagesc`

### ISSUE THREAD

**Issue by berceanu** [mbaz/Gaston.jl#32]
setting the `"xrange"` or `"yrange"` properties in `imagesc` results in
`Invalid property specified in imagesc at Gaston/src/gaston_hilvl.jl:445`

**Comment by mbaz** [comment]
Works for me on latest master with this code:

    using Gaston
    c = CurveConf()
    c.plotstyle = "image"
    Z = [5 4 3 1 0; 2 2 0 0 1; 0 0 0 1 0; 0 1 2 4 3]
    addcoords([],[],Z,c)
    a = AxesConf()
    a.title = "Image"
    a.xrange="[2:4]"
    a.yrange="[1:3.5]"
    addconf(a)
    llplot()
