### ISSUE TITLE
Saving to file crops the image

### ISSUE THREAD

**Issue by milktrader** [mbaz/Gaston.jl#4]
Using the example in the PDF docs. 

``` julia

julia> plot(sin(-pi:0.01:pi))
20

julia> set_filename("test.png")
"test.png"

julia> printfigure("png")
20
```

The original plot generated looks right, with the title and x and y labels. The saved file crops off the title, x-label and y-label

**Comment by rennis250** [comment]
I know that this is very old, but just so you know, it appears that everything works fine on a Homebrew installed gnuplot with the pangocairo terminal.

Best,
Rob

**Comment by mbaz** [comment]
@rennis250 Thanks a lot for the information. Just to clarify, do you mean that the 'aqua' terminal works fine with current gnuplot?
