### ISSUE TITLE
0.4.0-rc problem starting gnuplot

### ISSUE THREAD

**Issue by my-little-repository** [mbaz/Gaston.jl#41]
I just upgraded to julia 0.4.0-rc and checked out Gaston. Gnuplot does not start. 

      julia> Gaston.plot(sin(-pi:.01:pi))
      ERROR: There was a problem starting up gnuplot.
       in gnuplot_init at /home/yves/.julia/v0.4/Gaston/src/gaston_aux.jl:10
       in figure at /home/yves/.julia/v0.4/Gaston/src/gaston_hilvl.jl:94
       in plot at /home/yves/.julia/v0.4/Gaston/src/gaston_hilvl.jl:142

This could come from the instruction `Base.Pipe(C_NULL)` in the definition of popen3. This seems to raise an error now.

      julia> let x = Base.Pipe(C_NULL) ; print("ok") ; end
      ERROR: MethodError: `convert` has no method matching convert(::Type{Pipe}, ::Ptr{Void})
      This may have arisen from a call to the constructor Pipe(...),
      since type constructors fall back to convert methods.
      Closest candidates are:
        Pipe(::Any, !Matched::Any)
        call{T}(::Type{T}, ::Any)
        convert{T}(::Type{T}, !Matched::T)
        ...
       in call at essentials.jl:56

**Comment by mbaz** [comment]
Thanks for the report. I'm in the process of updating Gaston to work with
Julia 0.4. This is the first thing I'll need to fix.

**Comment by mbaz** [comment]
Fixed by https://github.com/mbaz/Gaston.jl/commit/6b7b673952f4b8fa5bbbedf88fb10cb0b3db5860
