### ISSUE TITLE
Errors (and warnings) when using Gaston with julia v 0.4

### ISSUE THREAD

**Issue by mgr58** [mbaz/Gaston.jl#42]
julia> using Gaston
Warning: Gaston has only been tested on gnuplot version 4.6
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:8
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:8
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:53
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:99
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl:117
ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
while loading /home/xxx/.julia/v0.4/Gaston/src/gaston_types.jl, in expression starting on line 161
while loading /home/xxx/.julia/v0.4/Gaston/src/Gaston.jl, in expression starting on line 26

This is happening with julia 0.4:

julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by mbaz** [comment]
Yes, Gaston is not 0.4-ready yet. I'm working on it but I don't have a lot
of time. Patches welcome :)

**Comment by mbaz** [comment]
Fixed by https://github.com/mbaz/Gaston.jl/commit/6b7b673952f4b8fa5bbbedf88fb10cb0b3db5860
