### ISSUE TITLE
Gaston package up-and-running in Windows 8/10 with gnuplot utility v5.0 (!!)

### ISSUE THREAD

**Issue by laborhm** [mbaz/Gaston.jl#45]
Here's a Gaston package version up-and-running with Julia 0.4.5 under Windows 8/10 with gnuplot utility v5.0. And it does run in Linux/Ubuntu 16.4, too.
[gaston_20_05_16_al.zip](https://github.com/mbaz/Gaston.jl/files/276845/gaston_20_05_16_al.zip)
A short instruction in the Gaston.jl file. 
Just do not know, how to "pull request" it. 
Cheers,
Andre Logunov

**Comment by mbaz** [comment]
Thanks for the report. I'll take a look at your changes and see about incorporating them into the mainline.

**Comment by mbaz** [comment]
@laborhm I tested current master with 0.4.6 on Windows 7 and everything seems to work. Please check it out and report any problems. You can check out master by running `Pkg.checkout("Gaston")` from inside Julia.

**Comment by laborhm** [comment]
issuing
  julia> Pkg.checkout("Gaston")
returns this:
ERROR: Gaston is not a git repo
 in checkout at pkg/entry.jl:203

2016-07-01 12:12 GMT+10:00 mbaz <notifications@github.com>:

**Comment by mbaz** [comment]
You may need to do `Pkg.add("Gaston")` first.

**Comment by laborhm** [comment]
I did that.

julia> Pkg.add("Gaston")
ERROR: unknown package Gaston
 [inlined code] from pkg/entry.jl:49
 in anonymous at task.jl:447
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

2016-07-01 12:49 GMT+10:00 mbaz <notifications@github.com>:

**Comment by laborhm** [comment]
By the way, my version works all right^

cd(joinpath(homedir(),"julia_projects","gaston","src"))
include("Gaston.jl")    #

using Gaston
g = Gaston;

c = g.CurveConf();
c.legend = "Произвольно";
c.plotstyle = "errorbars";
y = exp(-(1:.1:4.9));
ylow = y - 0.05*rand(40);
yhigh = y + 0.05*rand(40);
g.addcoords(1:40,y,c);
g.adderror(0.1*rand(40));
a = g.AxesConf();
a.title = "Значения ошибки (вертикальные отрезки)";
g.addconf(a);

g.llplot();

2016-07-01 13:25 GMT+10:00 Андрей Логунов <laborhm@gmail.com>:

**Comment by mbaz** [comment]
I don't know why `Pkg` can't find Gaston. Can you install other packages?

The way you install it is fine, but using Julia's package infrastructure
makes it easier for users to install, remove, and update packages.

**Comment by laborhm** [comment]
Yes, I can use the infrastructure. Using it I've installed about 180
packages, including Gaston. But Gaston from the very start didn't function
(under win10) until I copied it and made some updates manually as described.
To tell you more, I upgraded Julia from 0.4.5 to 0.4.6 and then Pkg.updated
the packages, and all of them work, except Gaston. An attempt to use it
produced "Package is dirty" massage. I deleted the folder
\.julia\v0.4\Gaston and tried to Pkg.add it. But still no go. I can only
use my version now.

2016-07-01 23:33 GMT+10:00 mbaz <notifications@github.com>:

**Comment by mbaz** [comment]
What do you get if you run `Pkg.status()` and look for the line about
Gaston? I get:

julia> Pkg.status()
1 required packages:
 - Gaston                        0.0.0+             master

Also, can you try `Pkg.remove("Gaston")` and then try to add it again?

**Comment by laborhm** [comment]
Pkg.status stops at Gaston:

julia> Pkg.status()
70 required packages:
 - ASCIIPlots                    0.0.3
 - AWS                           0.2.0
 - ArgParse                      0.3.0
 - Atom                          0.4.2
 - Blink                         0.3.4
 - Bokeh                         0.2.0
 - Calendar                      0.4.3
 - Clp                           0.2.1
 - Cosmology                     0.2.0
 - DSP                           0.0.11
 - DataFrames                    0.7.3
 - Debug                         0.1.6
 - DistributedArrays             0.2.0
 - Escher                        0.3.2
 - FITSIO                        0.8.3
 - FactCheck                     0.4.3
 - FileIO                        0.1.0
 - GLM                           0.5.2
 - GLVisualize                   0.0.9
 - GR                            0.10.0
 - Gadfly                        0.4.2
ERROR: KeyError: Gaston not found
 in pop! at dict.jl:767
 in status at pkg/entry.jl:122
 in status at pkg/entry.jl:139
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in status at pkg.jl:32 (repeats 2 times)

Writing Pkg.rm gives this:

julia> Pkg.rm("Gaston")
INFO: No packages to install, update or remove
INFO: Package database updated

2016-07-02 1:20 GMT+10:00 mbaz <notifications@github.com>:

> What do you get if you run `Pkg.status()` and look for the line about
> Gaston? I get:
>
> julia> Pkg.status()
> 1 required packages:
> - Gaston 0.0.0+ master
>
> Also, can you try `Pkg.remove("Gaston")` and then try to add it again?
>
>

**Comment by mbaz** [comment]
OK, if Pkg.status() errors out, I'm sure that means there is something
wrong with your package repository... Since you have a workaround, it may
not be worth it to try to fix it (not that I would know how to, short of
nuking your entire package folder and starting over).

For what it's worth, Gaston is working properly with Pkg on windows 7 here.

**Comment by laborhm** [comment]
You're right. Looks like it. I'll try to do sth about it and shall let you
know.


2016-07-02 1:44 GMT+10:00 mbaz <notifications@github.com>:

> OK, if Pkg.status() errors out, I'm sure that means there is something
> wrong with your package repository... Since you have a workaround, it may
> not be worth it to try to fix it (not that I would know how to, short of
> nuking your entire package folder and starting over).
>
> For what it's worth, Gaston is working properly with Pkg on windows 7 here.
>
>

**Comment by laborhm** [comment]
Here's the continuation (right after Pkg.rm() that I showed yesterday)

julia> Pkg.add("Gaston")
INFO: Installing Gaston v0.0.0
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of
Gaston
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using Gaston
Warning: Gaston has only been tested on gnuplot version 4.6
ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
while loading C:\Users\labor\.julia\v0.4\Gaston\src\gaston_types.jl, in
expression starting on line 161
while loading C:\Users\labor\.julia\v0.4\Gaston\src\Gaston.jl, in
expression starting on line 26

To mention again, I'm using gnuplot v.5.0

2016-07-02 1:48 GMT+10:00 Андрей Логунов <laborhm@gmail.com>:

**Comment by mbaz** [comment]
You need to use Gaston's master branch, by running
`Pkg.checkout("Gaston")`. I'll tag a new release soon, but in the meantime
only master is usable.

**Comment by laborhm** [comment]
Now everything's ok.

julia> Pkg.checkout("Gaston")
INFO: Checking out Gaston master...
INFO: Pulling Gaston latest master...
INFO: No packages to install, update or remove

julia> using Gaston
...

2016-07-02 14:18 GMT+10:00 mbaz <notifications@github.com>:

> You need to use Gaston's master branch, by running
> `Pkg.checkout("Gaston")`. I'll tag a new release soon, but in the meantime
> only master is usable.
>
>

**Comment by mbaz** [comment]
Good to know.

**Comment by laborhm** [comment]
My Russian translation of "Mastering Julia" by Sherrington (Packt) (amended
and updated to v0.4.6) is being published in Russia in july/august (
http://dmkpress.com/catalog/computer/programming/978-5-97060-370-3/).
B.R.

2016-07-03 8:57 GMT+10:00 mbaz <notifications@github.com>:

> Good to know.
>
>
