### ISSUE TITLE
Feature request: support for time series

### ISSUE THREAD

**Issue by milktrader** [mbaz/Gaston.jl#5]
I've seen several examples of using gnuplot for plotting time series. This functionality might already be exposed in `Gaston`.

````gnuplot
# a demonstration of gnuplot finance plot styles
# by John Bollinger, CFA, CMT
# www.BollingerBands.com
# BBands@BollingerBands.com

set title "Finance bars"
set yrange [75:105]
set ytics (105, 100, 95, 90, 85, 80)
set xrange [50:253]
set lmargin 9
set rmargin 2
set grid
set logscale y
plot 'finance.dat' using 0:2:3:4:5 notitle with financebars lt 8
````
This produces a plot that looks like this:

http://imgur.com/jcaMKcm

**Comment by mbaz** [comment]
Support added in https://github.com/mbaz/Gaston.jl/commit/f29f309fad3da51aea89b4badf3c49120c98905e

**Comment by milktrader** [comment]
NIce!

**Comment by mbaz** [comment]
Thanks! Sorry about the delay...
