### ISSUE TITLE
Gaston fails to load

### ISSUE THREAD

**Issue by nico202** [mbaz/Gaston.jl#51]
Hi, I wanted to try Gaston but couldn't.
My system:
* Linux asus_nixos 4.6.5 #1-NixOS SMP Wed Jul 27 15:42:34 UTC 2016 x86_64 GNU/Linux
* julia version 0.4.5
* gnuplot: Version 5.0 patchlevel 3    last modified 2016-02-21
* Gaston installed with Pkg.add("Gaston")

Running `using Gaston` leads to many deprecation warning
```
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/nixo/.julia/v0.4/Gaston/src/gaston_types.jl:117
```

and 
```

ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
while loading /home/nixo/.julia/v0.4/Gaston/src/gaston_types.jl, in expression starting on line 161
while loading /home/nixo/.julia/v0.4/Gaston/src/Gaston.jl, in expression starting on line 26
```

**Comment by nico202** [comment]
Ok found #38, using Pkg.checkout("Gaston") works. Maybe you can update the readme :)
Thanks!

**Comment by mbaz** [comment]
Thanks! Yeah, at this point only the master branch works. I hope to tag a
new release soon.

On Sat, Aug 27, 2016 at 5:01 AM, Nicolò Balzarotti <notifications@github.com
