### ISSUE TITLE
problem using Gaston under 0.5

### ISSUE THREAD

**Issue by my-little-repository** [mbaz/Gaston.jl#52]
I just downloaded the v0.5 julia binary. Gaston seems to load fine using `Pkg.add("Gaston"). It returns an error though if I use it.

```
julia> using Gaston
ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/***/.julia/v0.5/Gaston/src/gaston_types.jl, in expression starting on line 161
while loading /home/***/.julia/v0.5/Gaston/src/Gaston.jl, in expression starting on line 26
```

From the changelog, I can see that this is Gaston v0.5.5 that has been installed.
I think that Range1 was renamed UnitRange when v0.4 went stable. This looks ok on master.
So maybe the Gaston version packaged with julia should be upgraded?

**Comment by mbaz** [comment]
I haven't tested Gaston under v0.5 yet. However, in any case you want to use the master branch, which has seen tons of updates over the previous release. You can use `Pkg.checkout()` to get the latest Gaston.

**Comment by my-little-repository** [comment]
The master version works under v0.5. Thanks.

**Comment by fp4code** [comment]
To run all tests, don't run gaston_tests() as written in doc/gastondoc.tex. Instead, run Pkg.test("Gaston").
