### ISSUE TITLE
Improve commands syntax

### ISSUE THREAD

**Issue by mbaz** [mbaz/Gaston.jl#53]
I need to modernize the syntax of `plot` and similar commands -- right now they're really clunky.

Also, think about prefixing commands with `g` so that other plotting packages may be loaded at the same time.

**Comment by francilioaraujo** [comment]
How about using keyword arguments to pass the properties? I think it enhances the readability of function call and cleans the look of it. It might be even helpfull to validate the property values.

**Comment by mbaz** [comment]
Yep -- that's part of my plan. I just haven't had time to decide on a syntax and implement it. Help is welcome.

**Comment by francilioaraujo** [comment]
I'm willing to help. Could you send me an email at francilioaraujo@gmail.com so we can discuss some ideas?

**Comment by francilioaraujo** [comment]
How about the following syntax?

`plot({h,}({ x,} y {, ylow{, yhigh}}){, property, value...} {...})`

and

`plot({h,} x, y {, property, value...} {...})`

If one wants to plot `x` against `y` then the command `plot(x, y)` do it.  If one has `plot(a, b, c, d)` it would mean "plot `a` against `b` and `c` against `d`.
If one wants to use "special forms of coordinates", such as `(y)`, `(x, y, ydelta)` or `(y, ydelta)` then the coordinates must be passed inside a tuple (`(y, ylow, yhigh)` cause a confusion with `(x, y, ydelta)`, so only one must be accepted).

**Comment by mbaz** [comment]
Fixed in v0.7.0.
