### ISSUE TITLE
No histogram with Gaston on 0.6

### ISSUE THREAD

**Issue by my-little-repository** [mbaz/Gaston.jl#59]
The histogram functionality doesn't work any more under julia v0.6.0
I guess that this comes from the fact that the function `hist` has been removed from base.
There is instead a function `fit(Histogram, ...)` in the package StatsBase.

    julia> Gaston.histogram(randn(100000), "bins", 100, "norm", 1, "color", "gray")
    ERROR: UndefVarError: hist not defined
    Stacktrace:
    [1] histogram(::Array{Float64,1}, ::Vararg{Any,N} where N) at ~/.julia/v0.6/Gaston/src/gaston_hilvl.jl:283

**Comment by mbaz** [comment]
Thanks for the report. I may bring back my own histogram function, which was used in the early days of gaston, before julia had its own.
