### ISSUE TITLE
gnuplot 5.0.7 with julia 0.60 supported?

### ISSUE THREAD

**Issue by ErnestoZayas** [mbaz/Gaston.jl#60]
![asdasdasd](https://user-images.githubusercontent.com/31333095/30000075-29ce89e6-9014-11e7-8174-f0c8c9b445ca.JPG)

**Comment by mbaz** [comment]
Please explain your issue, how to reproduce it, etc. I can't tell that from a screenshot.

**Comment by ErnestoZayas** [comment]
i'm trying to download and test the package, but it doesn't works, i tried to comment those lines and try to test again ,now the test started but it showed "There was a problem starting up gnuplot" in each test.
the error are in this part of the code so why can't find gnuplot? 

# before doing anything else, verify gnuplot is present on this system
if !success(`gnuplot --version`)
    error("Gaston cannot be loaded: gnuplot is not available on this system.")
end

im ussing win 10, Julia 0.60, and now gnuplot 4.6
"C:\Program Files (x86)\gnuplot\bin\wgnuplot.exe"
"C:\Users\tento\.julia\v0.6"

i tried to with julia 0.52 too but it does the same.

**Comment by mbaz** [comment]
The problem may be that gnuplot is not on the path, or more likely, that for some reason it is called `wgnuplot.exe` instead of `gnuplot.exe`, which is what I would expect.

Can you try modifying the executable name to `wgnuplot` and see if it makes any difference?

**Comment by ErnestoZayas** [comment]
i tried and doesn,t work, but you gave me an idea.
Idk why but i paste all the docs inside bin folder of gnuplot on the test folder and it works
but using Gaston still without working

**Comment by mbaz** [comment]
Then, the problem is that gnuplot is not in the path. You can try adding it to the path (I don't know how to do that on Windows, but I'm sure instructions are available somewhere). Or, you can try specifying the entire path in Gaston. Let me know how it goes.

**Comment by ErnestoZayas** [comment]
i add C:\Program Files (x86)\gnuplot\bin to path environment variable, it wasn't there before, and it works like in #54 

Thank you.

**Comment by mbaz** [comment]
I'm glad you were able to get it to work. I'll add a note to the documentation about adding gnuplot to the path on windows.
