### ISSUE TITLE
Configuring for cygwin / mintty

### ISSUE THREAD

**Issue by hustf** [mbaz/Gaston.jl#61]
Glad to see the progress here!
I'm on windows, using cygwin. The terminal is called mintty. Gnuplot is installed, and I believe gnuplot is configured correctly (see screenshot). It looks like we can have inline plotting in the REPL with some help.

The test feedback, or trying to make a plot in the REPL result in:
 ```
julia> Pkg.test("Gaston")
INFO: Testing Gaston
WARNING: Gnuplot returned an error message:
WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
```

![image](https://user-images.githubusercontent.com/13949620/34457139-60868d02-eda8-11e7-8070-6cf921498bf2.png)

**Comment by mbaz** [comment]
This is very cool. I will add support for this terminal to Gaston.

**Comment by mbaz** [comment]
@hustf Could you please run a couple of tests on current Gaston master?

First try out the new "dumb" terminal, which produces an ascii plot:

    julia> using Gaston
    julia> set(terminal="dumb")
    julia> plot(1:10)

If this produces a plot, then please try out the "sixelgd" terminal:

    julia> set(terminal="sixelgd")
    julia> plot(1:10)

**Comment by hustf** [comment]
Sorry for the delay. Thanks for the 'dumb' terminal, already an improvement on Unicodeplots it seems. Here goes:
![image](https://user-images.githubusercontent.com/13949620/35877400-7ccba098-0b75-11e8-86ea-d95621caf716.png)


Follow-up:
![image](https://user-images.githubusercontent.com/13949620/35877550-e6270dd4-0b75-11e8-8bfd-6c3078838b7e.png)

**Comment by hustf** [comment]
...and after quitting and restarting Julia:
```
julia> Pkg.test("Gaston")
INFO: Testing Gaston
Test Summary: | Pass  Total
Pass expected |   62     62
WARNING: Gnuplot returned an error message:


gnuplot: unable to open display ''
gnuplot: X11 aborted.
Test Summary:    | Pass  Total
Failure expected |   47     47
Test Summary:   | Pass  Total
linestyle tests |    8      8
INFO: Gaston tests passed
```

**Comment by mbaz** [comment]
Thanks! Ignoring for the moment the test failures (which I can't reproduce), the fact that the output is printed to the screen instead of being interpreted by the terminal as SIXEL commands seems to indicate that there is some special mechanism to pass that data to the terminal. 

I have no idea what the mechanism is, and I can't research it at the moment for lack of time and lack of a cygwin installation. I'd be interested in any pointers you can find, since this is a cool feature and it'd be good to get it to work.

For the moment I'll leave the sixel terminal enabled in Gaston but I won't document it.

**Comment by hustf** [comment]
Unfortunately, I'm rather clueless at the moment and also a bit tied up the next month or so. Note to self, or somebody else keen on the bait, have a long look at both Gaston.jl internals, and also, for ideas or adaption:

https://github.com/Evizero/UnicodePlots.jl#low-level-interface

That interface ('canvas') works on both cygwin, windows repl terminal (at least with font DejaVu Sans mono), and VS Code terminal.

**Comment by mbaz** [comment]
Let's return to this when we have the time.

**Comment by hustf** [comment]
Changed behaviour with master after today's commit https://github.com/mbaz/Gaston.jl/commit/b4543d3d047112f839c5fbbd642439c121e4ebbb :

![image](https://user-images.githubusercontent.com/13949620/55342739-bf778c80-54a9-11e9-81f9-e9187f0f3699.png)

**Comment by hustf** [comment]
Ref. issue #61 (closed).

**Comment by mbaz** [comment]
Yep, I found a few bugs lingering about, and I'm trying to catch them all.

**Comment by mbaz** [comment]
@hustf Could you please re-try using master? Things are working fine for me here on xterm.

**Comment by hustf** [comment]
Ah, for example like this?
![image](https://user-images.githubusercontent.com/13949620/55349368-d0c89500-54b9-11e9-8262-65bc541d432b.png)

**Comment by mbaz** [comment]
Yeah -- that's it. Thanks for the help. (note that you can configure the plot size, font size, line color, etc just like with any other plot).

**Comment by mbaz** [comment]
What I think I'll do is let the user append arbitrary, additional terminal configurations; see #102. Gnuplot's terminals are so varied in the parameters they can take, that I hesitate to special case any of them.

I posted in the [recent thread on sixel plotting](https://discourse.julialang.org/t/plots-in-the-terminal-with-sixel/22503/12); I think I'll let that serve as an announcement.
