### ISSUE TITLE
add subplots support

### ISSUE THREAD

**Issue by CarloLucibello** [mbaz/Gaston.jl#72]
Is it possible to hande subplots in Gaston, as by `set multiplot ...` command in gnuplot?
If yes, an example should be add to the documentation

**Comment by mbaz** [comment]
I have no plans to support it, since it involves a lot of work and goes against Gaston's KIS philosophy. What would be a good use case for this?

**Comment by CarloLucibello** [comment]
not really: tipically I like more having a single window with subplots than many windows with different plots, but it doesn't change much

**Comment by mbaz** [comment]
I will leave this open while I give it a second thought.

**Comment by isentropic** [comment]
I (personally) have never seen good native (done within the package) multilayout plots. I think that it is better to nail single plot system first

**Comment by mbaz** [comment]
I've found a use case for this feature: generating multiple plots in Jupyter, from code in a single cell, or from a single @manipulate.

I'll add support for this (minimal) functionality in 0.11. As always, a pull request would be appreciated!

**Comment by mbaz** [comment]
Fixed in v1.0.0
