### ISSUE TITLE
savefigure problem with eps and pdf

### ISSUE THREAD

**Issue by CarloLucibello** [mbaz/Gaston.jl#74]
saving in eps and pdf formats as in
```julia
julia> plot(rand(10),rand(10),legend="ciao")
1

julia> printfigure(term="pdf", outputfile="test.pdf")
```
results in a pdf/eps with no axes and legend. 

For comparison look a this 
[test.pdf](https://github.com/mbaz/Gaston.jl/files/1681456/test.pdf)

compared to this
![test](https://user-images.githubusercontent.com/7014210/35620072-3fa4ec1e-0680-11e8-8958-6266cb352968.png)

**Comment by mbaz** [comment]
I can reproduce this.
