### ISSUE TITLE
install gnuplot binary

### ISSUE THREAD

**Issue by sdmcallister** [mbaz/Gaston.jl#78]
This is in relation to the following discussion:

https://discourse.julialang.org/t/suggested-minimal-requirements-for-short-term-plotting-solution/8877/33

Is it possible that `Pkg.add("Gaston")` would install the most recent/relevant Binary?

**Comment by mbaz** [comment]
I'm open to doing this, but: (1) I'm not convinced it's worth the effort, since gnuplot is trivial to install in essentially all OSs, and (2) I'd need somebody to do it, since I don't even know where to start doing this, and I don't have the time right now to learn how to.

**Comment by mbaz** [comment]
One more thought: gnuplot is GPL and Gaston is MIT-licensed. I'm assuming it's OK to bundle a GPL binary in an MIT package, but it'd be nice to have confirmation from somebody who understands the implications.

**Comment by musm** [comment]
Well this would also help with windows support through 
https://filehippo.com/download_gnuplot/

**Comment by mbaz** [comment]
I see little benefit for the potential gain and large amount of work involved here... I'll probably accept a pull request, but I need to be convinced that I can distribute a GPL binary along with a BSD package.
