### ISSUE TITLE
printfigure hangs gnuplot

### ISSUE THREAD

**Issue by PetrKryslUCSD** [mbaz/Gaston.jl#84]
I call printfigure after drawing some curves. The file is produced, but the actual figure window becomes unresponsive. 
```
using Gaston
ferrors = figure()
x = rand(5)
y = rand(5)
plot!(x, y, legend = "Approximate error", color = "blue", marker = Gaston.supported_markers[5])
figure(ferrors)
printfigure(handle = ferrors, term = "pdf", outputfile = "errors.pdf")
```

The window can be made to respond again by `figure(ferrors)`. 

I'm not sure if this is a bug or a feature.

**Comment by mbaz** [comment]
I think it's a bug (or at least an undesired behavior). I can reproduce it and I'll try to fix it.
