### ISSUE TITLE
Support 3D scatter plots

### ISSUE THREAD

**Issue by mbaz** [mbaz/Gaston.jl#88]
See if we can do better than plots.jl in this case: https://discourse.julialang.org/t/axes-attributes-labels-limits-not-working-in-3d-plots/10341

**Comment by kim-tom** [comment]
Thank you for amazing packages.
I wish I could use quiver and y2label.

**Comment by mbaz** [comment]
@kim-tom Thanks for the kind words. Please, open new issues for quiver and y2label support, and I'll take a look at what it takes to implement them.
