### ISSUE TITLE
Gaston possible on JuliaBox?

### ISSUE THREAD

**Issue by HenriLaurie** [mbaz/Gaston.jl#90]
I tried to get Gaston going on JuliaBox. Perhaps I was just impatient, but it wouldn't build. I wondered if this is because of the non-Julia dependency (gnuplot), or something else?

**Comment by mbaz** [comment]
I haven't tried, but Gaston does work on Jupyter, which I believe is what JuliaBox uses.

While I get around to testing it, could you please tell me what is the exact problem, i.e., what do you mean by "it wouldn't build"?

**Comment by mbaz** [comment]
OK, I just tried and I see what you mean by building. It builds a new system image incorporating the packages you want.

So my build finished successfully, but when trying `using Gaston` I got:

    LoadError: Gaston cannot be loaded: gnuplot is not available on this system.

There's nothing I can do about it. It may be worth it to ask the JuliaBox maintainers to add gnuplot to their system.

**Comment by HenriLaurie** [comment]
Thanks for response and sorry for the delay, I was offline and have to go
off again, just to say quickly that the JuliaBox way of adding a package is
to ask for it to be added, via the Packages option in the top line (the one
with one's login details at the top left). So when I did that it seemed to
me I had to click the Start button, which then launched a build that went
halfway quite quickly and then just seemed to freeze.

May be a JuliaBox issue? The connection and bandwidth here is rather flaky.

**Comment by mbaz** [comment]
@HenriLaurie The build finished successfully for me. Could you try again?

**Comment by HenriLaurie** [comment]
.... doesn't seem to be working, 12 mins in, will leave it running while I
go out for a while

**Comment by HenriLaurie** [comment]
Ok, it did build --- but using Gaston fails because gnuplot not installed,
trying Gnuplot.jl to see if it is any different. If not, should I open an
issue for JuliaBox? It seems to me that Gaston is the ideal way to deal
with the slowness of Plots, either for rapid low-quality graphics or for
beginners.

**Comment by HenriLaurie** [comment]
Oof. Can't install Gnuplot at all, it's not a registered package (well, it
doesn't autocomplete) and trying to install it unregistered fails (I don't
know why, and there seems to be no error log).

Well, this clearly isn't a Gaston issue, I'll see if I can get help from
the JuliaBox crowd. Thanks again! And thanks for Gaston, it seems vital
right now for people like me who have teaching to beginners in mind.

**Comment by mbaz** [comment]
@HenriLaurie Yes, it looks like there's nothing I can do on my side. One alternative for teaching would be to have students run Jupyter on their individual computers.
I have already reported this to the JuliaBox issue tracker: https://github.com/JuliaCloud/JuliaBox/issues/507

**Comment by HenriLaurie** [comment]
Yes. And yes --- I saw you did that, excellent thing.

**Comment by aviks** [comment]
Yes, GNUPlot is a native dependency, and needs to be added into the system image. We'll explore adding this to Juliabox.

**Comment by mbaz** [comment]
@aviks Thanks, Avik!

**Comment by HenriLaurie** [comment]
Thanks to @avik, @mbaz for getting started in May/June. Sadly, problems persist, in particular gnuplot (that is, the graphing utility program) is not available.

However, I see there is now a package Gnuplot 0.2.0 on JuliaBox, which I suspect is the private Github package associated with the user gcalderone. (There are two private Gnuplot.jl packages that come up when one searches with the term "Gnuplot.jl").

One can issue `using Gnuplot` in a JuliaBox 0.6.2 notebook run by JuliaBox; no error message follows. However, using gcalderone's simplest plot example `@gp 1:10` throws an error with a message about spawning gnuplot. This seems to indicate that the Gnuplot package available in JuliaBox is indeed the gcalderone one, and that gnuplot itself is still missing.

Is it possible that there has been some confusion between Gnuplot.jl and gnuplot itself?

**Comment by aviks** [comment]
> Is it possible that there has been some confusion between Gnuplot.jl and gnuplot itself?

Maybe, let me take a look.
