### ISSUE TITLE
Cannot plot a matrix directly

### ISSUE THREAD

**Issue by pemryan** [mbaz/Gaston.jl#92]
in Gaston 0.6,  
```
a = rand(9, 11)
plot(a)
```
works well.  exactly the same behavior as in Matlab.

it doesn't work out anymore in Julia 0.7, I check Gaston code, plot(a) will invoke:
`plot!(y::Coord;args...) = plot!(1:length(y),y;args...)`

**Comment by mbaz** [comment]
When I moved to the improved syntax, I removed support for plotting matrices directly. This shouldn't be too hard to re-implement; I'll put it in my todo list. In the meantime, you can work around the issue by plotting the first column with `plot()`, and then looping over the remaining columns with `plot!()`.
