### ISSUE TITLE
Gaston not working with Julia 0.7 nor with Julia 1

### ISSUE THREAD

**Issue by HenriLaurie** [mbaz/Gaston.jl#98]
It seems Gaston still fails with as per #93 for official 0.7 and 1.0. I have been trying both and I get that "There was a problem starting up gnuplot" message for both.

Might it be related to the fact they they are both in trial subdirectories of their own, in my home directory, while gnuplot itself is in /usr/bin?

**Comment by mbaz** [comment]
That shouldn't be a problem. I install Julia on my home directory myself.

Are you running Gaston master? Are you on windows? What happens if you run gnuplot from a terminal?

**Comment by HenriLaurie** [comment]
Thanks for the response, mbaz!

Not using master, using Pkg.add. This is deliberate, as I am hoping to
specify Gaston as the plotter for the update of my Julia Intro MOOC on
Coursera. (Also why I am hoping IJulia included gnuplot).

No, I use Linux (Manjaro, to be specific).

Just tried gnuplot from terminal, it starts and plots just fine (and seems
to exit properly as well).

(github not accessible to me atm, not sure why, using email)

**Comment by mbaz** [comment]
@HenriLaurie The latest tagged version is definitely not going to work. There are a lot of changes and improvements in master. However, there is one last remaining bug (#94) that has prevented me from issuing a new release. As soon as I can fix that one, I'll issue a release that should work with 0.7/1.0.

**Comment by HenriLaurie** [comment]
Great, thanks, really looking forward to that, Julia needs a lightweight plotting package and IMO Gaston is a very good candidate.

**Comment by mbaz** [comment]
Thanks for the kind words! I hope to make a new release very soon.

**Comment by HenriLaurie** [comment]
Any progress? We've now decided to re-record without using Gaston, but it is still my lightweight package of choice ... although it currently won't Pkg.add in Julia 1.0.1. I would love to be able to use it for teaching.

**Comment by mbaz** [comment]
@HenriLaurie Unfortunately I've had too much work these past few months. Gaston is on my urgent list of things to do, but something more urgent keeps coming up! Having said that, I have not abandoned Gaston by any means. Also, I'll gladly accept pull requests that help with the outstanding issues.

**Comment by HenriLaurie** [comment]
Actually, I'm only semi-literate in git-based collaboration*. So for me a painless way to get started would be "PR for documentation" i've seen mentioned. Is there a way for me to start on that? Will I have to get up to speed with GitKraken as Chris Rackauckas suggests, or is there a simpler way?

*I've always been a complete loner in computing projects. They've been scientific explorations, typically occasionally writing quite a few lines of code to set up an exploration environement, and then tinkering with parameters, initial conditions, outputs to get diagrams that seem to offer insight. I believe massively in open source and collaboration, but my personal practice has been otherwise.

**Comment by cosama** [comment]
I applied the required fixes to my fork as mentioned in #100. You can get a working version for `julia>0.7` with

```
using Pkg
Pkg.add(Pkg.PackageSpec(url="https://github.com/cosama/Gaston.jl", rev="fix-1.0"))
```

Hope that helps until @mbaz finds time to merge all the required changes.

Really cool project by the way.

**Comment by mbaz** [comment]
I just released version 0.9.0, which works for me using julia 1.1 and all tests pass. Please report any bugs and/or send me your PRs!

**Comment by HenriLaurie** [comment]
great, thanks very much Mbaz! Will use this in teaching next week, but
not yet sure about putting it in a MOOC ... but definitely still
hoping to do so.

**Comment by mbaz** [comment]
You're welcome! I hope Gaston behaves correctly in your classes.
