### ISSUE TITLE
Is Gaston still under maintenance?

### ISSUE THREAD

**Issue by waynelapierre** [mbaz/Gaston.jl#99]
I haven't used Julia for a while, last time when I did I was frustrated by the slow IDE Atom and slow plotting tools. I want to know if Gaston is still under maintenance? From its descriptions, it seems to be faster than Plots.jl but doesn't work on Julia 1.0.

**Comment by mbaz** [comment]
It is under maintenance, in the sense that it is still on my list of to-do things. I've had very little time to devote to it in the past few months, but I expect things will improve soon; lately, I've had some time to review the changes introduces by Julia 1.1 and I expect to have a Gaston release that works with it in a few weeks.
